apm-server:
  host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  ssl.verification_mode: "none"
  index: "apm-%{[{beat.version}]}"
  protocol: "http"
  username: "apm"
  password: "apmpass"